#!/bin/bash
set -e

cd /home/pi

apt-get update
apt-get install -y git

git clone https://github.com/my-dudhwala/my-KlipperScreen

# Ensure pi owns the directory
chown -R pi:pi my-KlipperScreen

# Run install script as pi user
sudo -u pi BACKEND="X" NETWORK="Y" bash my-KlipperScreen/scripts/KlipperScreen-install.sh