#!/bin/bash
set -xe
export LC_ALL=C

########################################
# Functions and Basic Configuration    #
########################################

source /common.sh
install_cleanup_trap

source /files/00-config

########################################
# Configuration                        #
########################################

SRC_DIR="/home/${BASE_USER}/KlipperScreen"
REPO="https://github.com/KlipperScreen/KlipperScreen.git"

DEPS=(git \
      python3 python3-pip python3-dev \
      libffi-dev libssl-dev \
      libjpeg-dev zlib1g-dev \
      libgl1-mesa-dev libglvnd-dev \
      libmtdev-dev \
      xinput x11-xserver-utils \
      libatlas-base-dev libopenblas-dev \
      )

########################################
# Install Dependencies                 #
########################################

echo "Installing Dependencies"
apt-get install --yes "${DEPS[@]}"

########################################
# Clone Repository                     #
########################################

pushd "/home/${BASE_USER}" &> /dev/null || exit 1

if [ ! -d "${SRC_DIR}" ]; then
  echo "Cloning KlipperScreen repo..."
  sudo -u "${BASE_USER}" git clone "${REPO}" KlipperScreen
else
  echo "KlipperScreen already exists, skipping clone."
fi

########################################
# Install Python Requirements          #
########################################

echo "Installing Python Requirements..."
sudo -u "${BASE_USER}" pip3 install -r "${SRC_DIR}/requirements.txt"

popd &> /dev/null || exit 1

########################################
# Copy and enable service              #
########################################

echo "Copy Service and enable it"
cp /files/klipperscreen.service /etc/systemd/system/klipperscreen@.service
systemctl_if_exists enable klipperscreen@${BASE_USER}.service
