#!/bin/bash
set -xe
export LC_ALL=C

########################################
# Functions and Basic Configuration    #
########################################

source /common.sh
install_cleanup_trap
source /files/00-config

########################################
# Configuration                        #
########################################

SRC_DIR="/home/${BASE_USER}/KlipperScreen"
REPO="https://github.com/my-dudhwala/my-KlipperScreen"
DEPS=(git python3 python3-pip python3-dev python3-gi \
      python3-gi-cairo gir1.2-gtk-3.0 libgtk-3-0 \
      xserver-xorg xinit x11-xserver-utils matchbox-window-manager \
      fonts-dejavu ttf-dejavu fonts-freefont-ttf \
      libatlas-base-dev libopenblas-dev)

########################################
# Install Dependencies                 #
########################################

echo "Installing dependencies for KlipperScreen..."
apt-get install --yes "${DEPS[@]}"

########################################
# Clone repository                     #
########################################

echo "Cloning KlipperScreen repo ..."
pushd /home/"${BASE_USER}" &> /dev/null || exit 1
sudo -u "${BASE_USER}" git clone ${REPO} KlipperScreen

########################################
# Install Python dependencies          #
########################################

echo "Installing Python dependencies..."
sudo -u "${BASE_USER}" pip3 install -r "${SRC_DIR}/scripts/KlipperScreen-requirements.txt"

########################################
# Setup Systemd Service                #
########################################

echo "Installing KlipperScreen service..."
cp "${SRC_DIR}/scripts/KlipperScreen.service" /etc/systemd/system/KlipperScreen.service
cp "${SRC_DIR}/scripts/KlipperScreen-start.sh" /home/"${BASE_USER}"/
chmod +x /home/"${BASE_USER}"/KlipperScreen-start.sh

# Adjust ownership
chown -R "${BASE_USER}":"${BASE_USER}" /home/"${BASE_USER}"/KlipperScreen

# Enable service
systemctl_if_exists enable KlipperScreen.service

########################################
# Return to saved directory            #
########################################

popd &> /dev/null || exit 1
