#!/bin/bash

set -e

# Load environment (USERNAME, etc.)
source /boot/config.txt || true

USERNAME=${USERNAME:-pi}
USER_HOME="/home/${USERNAME}"

echo "[install] Installing KlipperScreen..."

# Dependencies
apt-get update
apt-get install -y \
    python3-pip python3-dev python3-gi \
    python3-kivy libmtdev-dev \
    libgl1-mesa-dev xinput x11-xserver-utils \
    libffi-dev libssl-dev \
    libjpeg-dev zlib1g-dev

# Clone KlipperScreen repo if not already there
if [ ! -d "${USER_HOME}/KlipperScreen" ]; then
    sudo -u ${USERNAME} git clone https://github.com/my-dudhwala/my-KlipperScreen.git ${USER_HOME}/KlipperScreen
fi

# Install requirements
cd ${USER_HOME}/KlipperScreen
# sudo -u ${USERNAME} pip3 install -r requirements.txt
sudo -u ${USERNAME} pip3 install --break-system-packages -r requirements.txt


# Create systemd service
cat <<EOF >/etc/systemd/system/klipperscreen.service
[Unit]
Description=KlipperScreen
After=systemd-user-sessions.service display-manager.service

[Service]
User=${USERNAME}
WorkingDirectory=${USER_HOME}/KlipperScreen
ExecStart=${USER_HOME}/KlipperScreen/screen.py
Restart=always
Environment=XDG_RUNTIME_DIR=/run/user/%U

[Install]
WantedBy=graphical.target
EOF

# Enable service
systemctl enable klipperscreen.service

echo "[install] KlipperScreen installed and enabled."
